/* Internal shared declarations for the split analyzer (was one 8.4k-line
 * file): util (helpers) / infer (type inference) / scope (registration &
 * specialization) / pass (fixpoint passes) / analyze.c (driver). */
#ifndef SPINEL_ANALYZE_INTERNAL_H
#define SPINEL_ANALYZE_INTERNAL_H
#include "analyze.h"
#include "ffi_spec.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* The receiver class for a node inside an instance_eval/exec block, or -1. */
/* codegen_util.c's refusal, called from the analyzer too: declared here so
   no analyzer TU calls it undeclared (an implicit `int` prototype, which a
   wasm link reports as a signature mismatch and an LP64 link hides) */
__attribute__((noreturn)) void unsupported_feature(Compiler *c, int id, const char *msg);
int ie_class_of(Compiler *c, int node);
int attr_reader_ty(Compiler *c, int cid, const char *name, TyKind *out);
int ie_poly_classes_at(Compiler *c, int node, int *out, int max);
/* Does the program make a bare Object (`Object.new`)? (analyze_infer.c) */
int an_program_news_object(Compiler *c);
int ie_kernel_global(const char *n);

/* Forward declarations for FFI helpers defined later in this file. */
const char *ffi_arg_str(const NodeTable *nt, int nid);
int ffi_arg_int(const NodeTable *nt, int nid);
TyKind ffi_spec_to_ty(const char *spec);
int ffi_find_func(Compiler *c, const char *mod, const char *name);
int ffi_find_buf(Compiler *c, const char *mod, const char *name);
int ffi_find_reader(Compiler *c, const char *mod, const char *name);
int ffi_find_writer(Compiler *c, const char *mod, const char *name);


/* Re-entrancy guard for yield_value_type: prevents infinite recursion when a
   recursive method forwards its block to itself (e.g. countdown { blk.call }). */
#define MAX_YVT_DEPTH 32
extern int g_yvt_mi[MAX_YVT_DEPTH];
extern int g_yvt_depth;

/* Temporary class override for instance_eval block body inference.
   -1 = no override; set to the receiver's class_id while inferring
   the block body so that InstanceVariableReadNode uses the right class. */
extern int an_ie_class_id;
/* Class index of the class/module body currently being analyzed (set around
   ClassNode/ModuleNode body traversal). -1 outside any class body. */
extern int g_cbody_class_id;
/* Like g_cbody_class_id, but cleared when descending into a method/block scope:
   the class index only while walking a class/module body's *direct* statements,
   where `self` is the class object. -1 inside method bodies and at top level.
   Mirrors codegen's g_class_body_id so a self/bare `class_eval` reopen is
   recognized identically by analyze and codegen. */
extern int g_cbody_direct;


/* method(:sym) helpers (defined in analyze_util.c, shared with codegen) */
const char *method_sym_arg(Compiler *c, int node);
int is_method_obj_call(Compiler *c, int node);
int method_obj_target_mi(Compiler *c, int node);
int method_recv_node(Compiler *c, int recv);
int method_recv_nodes(Compiler *c, int recv, int **out);
int method_expr_is_unbound(Compiler *c, int recv);
int proc_to_proc_method_nodes(Compiler *c, int recv, int **out);
int local_sole_range_node(Compiler *c, int recv);
int const_array_elems_all_int_array(Compiler *c, const char *cname);
int *an_parent_map(const NodeTable *nt);
int an_value_dropped(const NodeTable *nt, const int *parent, int node);
int local_all_writes_empty_hash(Compiler *c, Scope *sc, const char *name);
int local_all_writes_empty_hash_or_new(Compiler *c, Scope *sc, const char *name);
int method_call_param_shift(Compiler *c, int mn, int mi);

extern int g_inc_did_clone;
extern int *g_ie_node_class;

typedef struct { const char **v; int n, cap; } ANameSet;
#define QC_MAXDEPTH 8
typedef struct { int node; char path[QC_MAXDEPTH][64]; int depth; char name[128]; } QCWrite;

/* ---- cross-part function declarations (generated by the split) ---- */
int is_builtin_class_name(const char *n);
void refuse_unreachable_bare_constants(Compiler *c);
int is_builtin_module_name(const char *n);
int is_builtin_exception_name(const char *n);
const char *superclass_builtin_exc_name(const NodeTable *nt, int sc);   /* analyze_util.c */
int is_syserr_family_name(const char *n);           /* analyze_util.c */
int builtin_method_known(const char *cls, const char *m);
int builtin_method_names(const char *cls, const char **out, int cap);
int builtin_arity_violation(Compiler *c, int id);
int is_handler_proc_block(Compiler *c, int id);
int builtin_class_id(const char *name);
int builtin_class_parent_id(int id);
int desugar_builtin_reopen_named_superclass(Compiler *c);
const char *class_ruby_name(Compiler *c, int ci); /* codegen.c */
int builtin_object_method_known(const char *m);
int core_method_name(const char *n);   /* analyze_desugar.c: a core class's public method */
int class_inherits_builtin_exception(Compiler *c, int ci);
int an_user_defines_or_reads(Compiler *c, const char *name);
/* The universal "what a receiver answers" table (analyze_infer.c) and the
   lookup its consumers use. See the note on AN_POLY_RAW. */
struct an_poly_raw_row { const char *n; int ac; TyKind t; };
extern const struct an_poly_raw_row AN_POLY_RAW[];
int an_poly_raw_argc(const char *name);
/* 1 when a user class defines `name` as an instance method whose return is not
   `want`: the poly dispatch accumulates its arm beside the builtin ones in one
   C temp, so the call must be typed for what both can hold. */
int an_user_ret_disagrees(Compiler *c, const char *name, TyKind want);
int an_ty_holds_nil(TyKind t);
int gvar_seeded_before_read(Compiler *c, const char *gname);
int an_empty_container_kind(Compiler *c, int b);
int an_empty_container_disagrees(int kind, TyKind other);
int an_or_empty_hash_fallback(Compiler *c, int node);
int an_chunk_family_to_a(Compiler *c, int id);
const char *an_regex_lit_src(Compiler *c, int nid);
int str_in(const char *s, const char *const *set);
int an_unparen(const NodeTable *nt, int n);
int blk_locals_have(const char *locals, const char *nm);
/* The calls named `name`, ascending: for (id = an_calls_named_first(c, nm);
   id >= 0; id = an_calls_named_next(id)). Check each node as before. */
int an_calls_named_first(Compiler *c, const char *name);
int an_calls_named_next(int id);
int is_arith_op(const char *op);
int node_is_empty_container(const NodeTable *nt, int node);
int bind_coerce_operator_params(Compiler *c);
int is_cmp_op(const char *op);
int is_numeric_coerce_op(const char *op);
int class_coerce_emittable(Compiler *c, int k);
int class_has_coerce_shape(Compiler *c, int k);
int class_has_to_str_shape(Compiler *c, int k);
int is_eq_op(const char *op);
int is_void_call(const char *name);
/* The enclosing scope's own chain owns this receiverless call's name, so no
   Kernel arm may claim it (the codegen twin is bare_call_class_owned). */
int an_bare_call_class_owned(Compiler *c, int id);
/* Resolve a struct member from a literal key node: a SymbolNode names a
   member; an IntegerNode is a positional index. Returns the member index
   (0-based, matching ivar order) or -1. */
int struct_member_idx(Compiler *c, ClassInfo *sc, int keynode);
int struct_member_idx_float(Compiler *c, ClassInfo *sc, int keynode);
/* Last statement of a scope's body, or -1. */
int scope_body_last(Compiler *c, int mi);
/* 1 if `node` is `<&block-param>.call(...)` / .() / [] for method mi -- the
   explicit-call equivalent of `yield`, inlined the same way. */
int is_blk_param_call(Compiler *c, int node, int mi);
/* Scan a subtree for BreakNode values and return their unified type.
   Stops at DefNode/BlockNode boundaries (inner blocks have their own break scope). */
TyKind scan_break_type(Compiler *c, int id, int depth);
/* Unify the value types of every `throw <tag>, <val>` inside a catch block.
   A nested inner BlockNode is still scanned because `throw` is dynamic. */
TyKind scan_throw_type(Compiler *c, const char *tag);
/* The value type of `yield` / a `<&block-param>.call` inside method mi: the
   block-body value type at a (any) call site of mi. Polymorphic, resolved from
   the first matching caller -- matches how the rewrite inlines per call site. */
TyKind yield_value_type(Compiler *c, int mi);
/* Tail expressions of the blocks reaching `mi`'s yield (see analyze_util.c). */
int yield_block_tails(Compiler *c, int mi, int *out, int max);
/* The block value reaching `mi` from a child's `super` (see analyze_util.c). */
TyKind yield_value_type_via_super(Compiler *c, int mi);
int yield_value_diverges(Compiler *c, int mi);
TyKind yield_aware_elem_ty(Compiler *c, int node);
int an_user_defines_method(Compiler *c, const char *name);
int an_user_recv_defines_method(Compiler *c, const char *name);
extern int g_yvt_unify_all;
/* The return type of a call to method `mi`. A method whose body is just a
   bare `yield` returns the block's value -- and since it inlines per call
   site, use THIS site's block value type rather than the unified return. */
TyKind method_call_ret(Compiler *c, int mi, int call_id);
/* A program's own Object method serving a call on a builtin receiver of
   class `cls` that does not have the name itself (see analyze_infer.c). */
int object_reopen_answers(Compiler *c, const char *cls, int call_id, TyKind *out);
/* is_proc_constant / is_proc_literal are declared in analyze.h (codegen needs them). */
/* 1 if `id` is any proc-creating literal: a proc/lambda/Proc.new call (above)
   or a `->(){}` LambdaNode. */
int is_proc_create(Compiler *c, int id);

/* Shared cached local-write index (analyze_pass.c): bucket walk over
   (scope, name) for "every write of local X in scope S" queries, instead of
   a whole-table rescan per query. Callers must still confirm scope/name
   (hash collisions) and node kind on each record. */
int lw_shared_first(Compiler *c, const char *name, int scope);
int lw_shared_node(int rec);
int lw_shared_next(int rec);
/* Nil narrowing (analyze.c): the facts for a round of the nullable marking,
   and the start of a type-inference round, whose facts are computed when
   first asked. */
void nn_compute(Compiler *c, int round);
void nn_inference_round(Compiler *c);
/* Shared cached ivar-write index (analyze_pass.c): the ivar analogue of the
   local-write index, keyed by ivar name only. Callers confirm name (hash
   collisions), node kind, and defining class on each record. */
int ivw_shared_first(Compiler *c, const char *name);
int ivw_shared_node(int rec);
int ivw_shared_next(int rec);
/* The body return type of a proc-creating node (proc/lambda CallNode literal,
   or a LambdaNode). The last statement of the block/lambda body is the value. */
TyKind proc_node_ret(Compiler *c, int create);
/* The body return type (`#call`'s result) of a proc-valued expression, or
   TY_UNKNOWN if not statically known. Resolves a literal directly, a local's
   recorded proc_ret, and a method call's recorded ret_proc_ret. */
TyKind proc_ret_of(Compiler *c, int node);
/* The return type of a proc-typed expression's `.call`; poly when unknown. */
TyKind proc_call_ret(Compiler *c, int recv);
TyKind infer_call(Compiler *c, int id);
TyKind infer_uncached(Compiler *c, int id);
void scope_add_param(Scope *s, const char *name, int defnode);
void collect_def_params(Compiler *c, int def_id, Scope *s);
char *dm_lit_str(Compiler *c, int lit);
char *dm_eval_name(Compiler *c, int node, const char *bv, int lit);
TyKind dm_lit_type(Compiler *c, int lit);
int collect_dm_each_unroll(Compiler *c, int id, int class_id);
const char *builtin_class_of_type(TyKind t);
const char *resolve_class_alias(Compiler *c, const char *cname);
void walk_scope(Compiler *c, int id, int scope_idx, int class_id);
int scope_own_defaults(Compiler *c, int di);
void register_module_functions(Compiler *c);
void register_method_visibility(Compiler *c);
void register_locals(Compiler *c);
int is_struct_call(Compiler *c, int val);
int class_body_list(Compiler *c, int **out_ci, int **out_body);
int class_def_body(Compiler *c, int def_node);
void register_struct_members(Compiler *c, ClassInfo *cls, int val);
void register_structs(Compiler *c);
void register_singleton_defs(Compiler *c);
void fix_struct_block_scopes(Compiler *c);
void register_attr_call(Compiler *c, ClassInfo *cls, int s, int singleton);
void register_attrs_body(Compiler *c, ClassInfo *cls, int body);
void register_attrs(Compiler *c);
void register_aliases_body(Compiler *c, ClassInfo *cls, int body);
void register_aliases(Compiler *c);
void register_undefs_body(Compiler *c, ClassInfo *cls, int body);
void register_undefs(Compiler *c);
int is_c_ident(const char *s);
void register_globals_consts(Compiler *c);
const char *ffi_arg_str(const NodeTable *nt, int nid);
int ffi_arg_int(const NodeTable *nt, int nid);
TyKind ffi_spec_to_ty(const char *spec);
void register_ffi_decls(Compiler *c);
int ffi_find_func(Compiler *c, const char *mod, const char *name);
int ffi_find_buf(Compiler *c, const char *mod, const char *name);
int ffi_find_reader(Compiler *c, const char *mod, const char *name);
int ffi_find_writer(Compiler *c, const char *mod, const char *name);
int infer_global_const_types(Compiler *c);
int infer_multiwrite_const_types(Compiler *c);
int masgn_tuple_rhs(const NodeTable *nt, int value);
int multi_return_elem_types(Compiler *c, int value, TyKind *out, int max);
void resolve_parents(Compiler *c);
void resolve_inherited_aliases(Compiler *c);
void process_include_body(Compiler *c, int ci, int body_node);
void register_includes(Compiler *c);
void register_include_attrs(Compiler *c);
void rewrite_attr_supers(Compiler *c);
void unmark_referenced_module_sources(Compiler *c);
void register_extends(Compiler *c);
int cmethod_has_bare_new(Compiler *c, int mi);
int cmethod_needs_specialization(Compiler *c, int mi, int ci, int def_cls, int *has_new);
int class_value_escapes(Compiler *c, int cid);
void specialize_inherited_cls_new(Compiler *c);
void register_prepends(Compiler *c);
void inherit_members(Compiler *c);
int infer_inherited_ivars(Compiler *c);
int infer_cvar_types(Compiler *c);
int infer_ivar_types(Compiler *c);
/* 1 if `name` (incl '@') is an ivar pinned by an --rbs seed in class `ci`;
   the ivar inference write sites consult this to avoid widening a pinned slot. */
int class_ivar_pinned(ClassInfo *ci, const char *name);
void class_unpin_ivar(ClassInfo *ci, const char *name);
void sp_ivwatch(const char *name, const char *where, TyKind old, TyKind nw);
void sp_narrow_memo_bump(void);
int infer_write_types(Compiler *c);
void seed_unsupplied_nil_defaults(Compiler *c);
int infer_container_flow(Compiler *c);
int an_builtin_only_p(void);
TyKind an_builtin_answer(Compiler *c, int id);
int an_yield_site_builtin_answer(Compiler *c, int id, TyKind kind, TyKind *out);
int poly_expr_flows_container(Compiler *c, int node);
int reconcile_locals_reading_ivars(Compiler *c);
int widen_object_locals_from_poly_writes(Compiler *c);
int widen_arrays_from_map_bang(Compiler *c);
void intern_block_params(Compiler *c);
int local_all_writes_empty_array(Compiler *c, Scope *sc, const char *name);
int infer_param_hash_value(Compiler *c);
int bind_call_params(Compiler *c, int call_id, int mi);
int param_src_misfits(Compiler *c, Scope *m, LocalVar *p, TyKind ct, const int *argv,
                      const ArgLayout *L);
void call_layout(Compiler *c, Scope *m, const int *argv, int argc, ArgLayout *L);
int layout_plain_arg(Compiler *c, Scope *m, const int *argv, const ArgLayout *L, int i);
int call_param_arg(Compiler *c, Scope *m, const int *argv, int argc, int i);
int unassigned_param_read(Compiler *c, Scope *sc, int n);
int param_rest_misfits(Compiler *c, Scope *m, LocalVar *p, TyKind ct, const int *argv, int an);
int opt_before_required(Compiler *c, Scope *m);                 /* codegen_fold.c */
int arg_slot_for_param(Compiler *c, Scope *m, int idx, int argc); /* codegen_fold.c */
int arg_layout_plain_arg(Compiler *c, Scope *m, int pos_argc, int i); /* codegen_fold.c */
int arg_layout_param_node(Compiler *c, Scope *m, int call, int i, int *spread); /* codegen_fold.c */
int zsuper_param_source(Compiler *c, Scope *s, Scope *pm, int j);         /* codegen_fold.c */
int rest_packable_arm(Compiler *c, Scope *s);                    /* codegen_fold.c */
/* The type a READ of ivar slot `iv` yields (a shared-mutable string slot
   reads as a plain String). Shared with the receiver-face helpers. */
TyKind ivar_value_ty(ClassInfo *ci, int iv);
int infer_range_call(Compiler *c, int id, TyKind rt, TyKind *out);
int infer_poly_call(Compiler *c, int id, TyKind rt, TyKind *out);
int infer_object_call(Compiler *c, int id, TyKind rt, TyKind *out);
int infer_array_call(Compiler *c, int id, TyKind rt, TyKind *out);
int infer_hash_call(Compiler *c, int id, TyKind rt, TyKind *out);
int infer_numeric_call(Compiler *c, int id, TyKind rt, TyKind *out);
/* The array a map-shaped call answers from its block's tail (analyze_infer_recv.c). */
TyKind infer_map_block_ty(Compiler *c, int id, int block);
/* A range endpoint that is the infinite Float constant (analyze_infer.c). */
int infer_end_is_float_inf(Compiler *c, int right);
int propagate_prep_params(Compiler *c);
int an_program_spawns_threads(Compiler *c);
int infer_default_param_types(Compiler *c);
int is_string_only_method(const char *m);
int infer_params_from_ivar_hash_ops(Compiler *c);
int infer_hash_params(Compiler *c);
int infer_array_params(Compiler *c);
int infer_string_params(Compiler *c);
int infer_param_types(Compiler *c);
int infer_for_index(Compiler *c);
int infer_catch_block_params(Compiler *c);
void infer_bigint_loop_locals(Compiler *c);
void block_sites_index(Compiler *c);
int block_sites(Compiler *c, int si, const int **sites);
int block_site_args(Compiler *c, int si, int site, int call);
int a_super_target(Compiler *c, Scope *m);
/* A block's (or a proc literal's) parameters as its binders count them:
   P leading requireds, O optionals, Q posts, R a rest marker (`*r`, `*`,
   a trailing comma), nk keywords; kw when a trailing keyword hash goes to
   the keywords (named ones, or any `**`), never to a positional. */
typedef struct { int pn, num, P, O, Q, R, nk, kw, lambda; } BlockSig;
void block_sig(Compiler *c, int params, int lambda, BlockSig *s);
const char *block_sig_name(Compiler *c, const BlockSig *s, int i);
const char *block_sig_kw_name(Compiler *c, const BlockSig *s, int k);
/* What block_site_types records per positional beside its type: a site may
   leave it without a value (BS_ABSENT), or pass it a literal nil (BS_NIL). */
enum { BS_ABSENT = 1, BS_NIL = 2 };
void block_site_types(Compiler *c, const BlockSig *s, const int *av, int ac,
                      TyKind *pos, char *absent, TyKind *kws);
int block_settle_types(Compiler *c, int blk, const BlockSig *s,
                       const TyKind *pos, const char *absent, const TyKind *kws);
int a_proc_params_node(Compiler *c, int create);
int infer_block_params(Compiler *c);
int narrow_site_boxed_block_params(Compiler *c);
int desugar_to_proc_block_arg(Compiler *c);
int desugar_proc_expr_block_arg(Compiler *c);
int desugar_to_hash_splat(Compiler *c);
int desugar_splat_to_a(Compiler *c);
int desugar_lazy_method_call(Compiler *c);
int desugar_value_callable_forwards(Compiler *c);
int desugar_root_scoped_constants(Compiler *c);
int desugar_errno_aliases(Compiler *c);
const char *errno_canonical_name(const char *n);   /* analyze_util.c */
void desugar_class_reopen(Compiler *c);
int desugar_def_unless_method_defined(Compiler *c);
int desugar_class_body_self_calls(Compiler *c);
int desugar_builtins(Compiler *c);
void desugar_stored_enum_each(Compiler *c);
int desugar_enum_walk_calls(Compiler *c);
int desugar_index_op_write_user(Compiler *c);
int desugar_main_self_call(Compiler *c);
int desugar_cmethod_cvar_reflection(Compiler *c);
int desugar_builtin_enum_calls(Compiler *c);
int desugar_builtin_scalar_defs(Compiler *c);
int desugar_builtin_scalar_calls(Compiler *c);
/* Block iterator the nested-table narrow pass keeps. each / map / zip stay
   on the typed emitter. each_with_index / reduce / inject are rewritten
   onto builtins/enumerable.rb; the copy's own each is what walks the table. */
int nested_row_iter_call(Compiler *c, int id);
int fold_static_is_a(Compiler *c);
int narrow_empty_array_args_by_yield(Compiler *c);
int builtin_enum_name_index(const char *name);
int an_class_includes_enumerable(Compiler *c, int ci);
int desugar_block_destructure_params(Compiler *c);
int desugar_for_nonlocal_index(Compiler *c);
int desugar_block_implicit_rest(Compiler *c);
int desugar_multi_value_jump(Compiler *c);
int desugar_forwarding_to_rest_callee(Compiler *c);
int desugar_anon_block_param(Compiler *c);
int desugar_singleton_class_define_method(Compiler *c);
int desugar_define_method_proc_arg(Compiler *c);
int desugar_define_method_captures(Compiler *c);
int desugar_define_method_keywords(Compiler *c);
void desugar_extended_module_attrs(Compiler *c);
int desugar_recursive_param_defaults(Compiler *c);
int desugar_param_default_assigns_local(Compiler *c);
int desugar_sort_by_with_index(Compiler *c);
int desugar_enumerable_via_to_a(Compiler *c);
int desugar_public_method(Compiler *c);
int desugar_class_eval_value(Compiler *c);
int desugar_instance_eval_builtin(Compiler *c);
int desugar_builtin_class_var_recv(Compiler *c);
int desugar_class_body_bare_new(Compiler *c);
int desugar_bare_class_self_calls(Compiler *c);
int desugar_ie_bare_object_calls(Compiler *c);
int desugar_bare_object_reopen_calls(Compiler *c);
int desugar_descendant_reader_calls(Compiler *c);
int desugar_match_predicate(Compiler *c);
int desugar_masgn_store_evidence(Compiler *c);
int desugar_blk_param_writes(Compiler *c);
int desugar_rest_param_writes(Compiler *c);
int desugar_yield_in_closure(Compiler *c);
int desugar_index_assign_user_recv(Compiler *c);
int desugar_const_attr_op_assign(Compiler *c);
int desugar_safe_nav_attr_write(Compiler *c);
int desugar_body_self_call(Compiler *c);
int desugar_body_module_eval(Compiler *c);
int desugar_extend_self(Compiler *c);
int desugar_kernel_reopen(Compiler *c);
int desugar_singleton_class_mixin(Compiler *c);
int desugar_singleton_attr(Compiler *c);
int desugar_constant_path_self_alias(Compiler *c);
int desugar_dynamic_const_get_arms(Compiler *c);
int desugar_reopen_implicit_self(Compiler *c);
int desugar_handle_attr_accessor(Compiler *c);
int desugar_handle_reopen_self_recv(Compiler *c);
int desugar_call_or_write_reopen(Compiler *c);
int desugar_static_class_eval(Compiler *c);
int desugar_compose_method_operand(Compiler *c);
int desugar_mutator_receiver_value(Compiler *c);
int desugar_method_curry(Compiler *c);
int desugar_curry_arity_to_int(Compiler *c);
int desugar_int_enum_with_index(Compiler *c);
int widen_shared_cmp_params(Compiler *c);
int desugar_reduce_proc_arg(Compiler *c);
int desugar_block_capture_wrap(Compiler *c);
int desugar_user_not_match(Compiler *c);
int desugar_env_enum(Compiler *c);
int desugar_dir_surface(Compiler *c);
const char *builtin_class_var_static_name(Compiler *c, int node);
int local_write_binds_value(NodeKind k);
int desugar_enumerable_chain(Compiler *c);
int desugar_implicit_send(Compiler *c);
int desugar_public_send_recv(Compiler *c);
int type_block_rest_params(Compiler *c);
void check_block_rest_support(Compiler *c);
int desugar_dynamic_send(Compiler *c);
void expand_static_splat_args(Compiler *c, int from, int count);
int desugar_dynamic_method(Compiler *c);
int desugar_method_call_runtime_name(Compiler *c);
int desugar_engine_branches(Compiler *c);
int desugar_conditional_defs(Compiler *c);
int desugar_dynamic_respond_to(Compiler *c);
int desugar_toplevel_instance_exec(Compiler *c);
int desugar_binding_lvget(Compiler *c);
int desugar_rightward_pattern(Compiler *c);
int desugar_step_kwargs(Compiler *c);
int desugar_defined_method_call(Compiler *c);
int desugar_respond_to_probe(Compiler *c);
int desugar_symbol_to_proc_call(Compiler *c);
int desugar_call_op_write(Compiler *c);
int desugar_array_at(Compiler *c);
int desugar_array_first_last(Compiler *c);
int desugar_enum_iter_splat_args(Compiler *c);
int desugar_builtin_iter_block_shapes(Compiler *c);
int desugar_enum_pair_lone_param(Compiler *c);
int sym_block_values(Compiler *c, int id);
void mark_sym_proc_blocks(Compiler *c);
void enum_hop_yield_view(Compiler *c, int id, int hop);
int sym_proc_poly_pair_view(Compiler *c, int id);
int desugar_to_h_block(Compiler *c);
int desugar_ffi_library_functions(Compiler *c);
int comp_ffi_library_module(const NodeTable *nt, const char *mn);
int rewrite_ffi_dynamic_calls(Compiler *c);
int desugar_builtin_reopen_self_calls(Compiler *c);
int desugar_builtin_reopen_methods(Compiler *c);
int desugar_object_method_builtin_overrides(Compiler *c);
int desugar_body_ivars(Compiler *c);
void mark_match_ranges(Compiler *c);
int desugar_duplicate_underscore_params(Compiler *c);
int desugar_encoding_queries(Compiler *c);
int desugar_alias_method_string_names(Compiler *c);
int desugar_alias_method_values(Compiler *c);
int desugar_inherited_aliases(Compiler *c);
int desugar_reader_aliases_before_redef(Compiler *c);
int desugar_reassigned_block_params(Compiler *c);
int desugar_class_new_blocks(Compiler *c);
int desugar_included_hooks(Compiler *c);
int desugar_self_const_get(Compiler *c);
int desugar_dynamic_const_get(Compiler *c);
TyKind return_node_type(Compiler *c, int id);
int infer_return_types(Compiler *c);
int backprop_hash_return_types(Compiler *c);
int backprop_call_target(Compiler *c, int call_id);
int ivar_src_slot(Compiler *c, int v, const char **ivn);
void cr_collect_calls(Compiler *c, const NodeTable *nt, int id, char ***out, int *n, int *cap);
void compute_reachable(Compiler *c);
void compute_instantiated(Compiler *c, int early);
int aname_has(ANameSet *s, const char *nm);
void aname_add(ANameSet *s, const char *nm);
/* A hashed name set (keys borrowed, not copied); zero-initialize to start. */
typedef struct { const char **key; int *next, *head, n, cap, nb; } ANameHash;
int anh_has(const ANameHash *st, const char *nm);
int anh_find(const ANameHash *st, const char *nm);   /* insertion index, or -1 */
void anh_add(ANameHash *st, const char *nm);
void anh_free(ANameHash *st);
int a_nested_block(const char *ty);
int a_is_local_node(const char *ty);
int a_is_write_node(const char *ty);
void a_mark_subtree(Compiler *c, int id, char *inproc);
void a_collect_used(Compiler *c, int id, ANameSet *out);
int a_proc_params_node(Compiler *c, int create);
int a_proc_body(Compiler *c, int create);
int a_block_is_lifted(Compiler *c, int id);
int a_proc_create_or_lifted(Compiler *c, int id);
void mark_proc_captures(Compiler *c);
void bigint_scan_body(const NodeTable *nt, int id, char ***names, int *n, int *cap);
void detect_bigint_loop_vars(Compiler *c);
void propagate_bigint_cascade(Compiler *c);
void mark_ie_subtree(Compiler *c, int node, int cls);
void build_ie_map(Compiler *c);
int ie_block_body(Compiler *c, int blk);
int ie_class_of(Compiler *c, int node);
int blkp_params_node(Compiler *c, int create);
int blkp_binds_param(Compiler *c, int create, const char *name);
void blkp_rewrite_refs(Compiler *c, int node, const char *oldn, const char *newn);
void numbered_rename_locals_str(NodeTable *nt, int L, const char *from, const char *to);
void blkp_mark_subtree(const NodeTable *nt, int node, char *marks);
int blkp_needs_rename(Compiler *c, int L);
void qc_collect_writes(Compiler *c, int node, char (*path)[64], int depth, QCWrite **ws, int *n, int *cap);
int qc_read_chain(const NodeTable *nt, int node, char (*chain)[64], int *abs_anchor);
void qc_qualified_name(char *out, size_t cap, const QCWrite *w);
void qc_rewrite_reads(Compiler *c, int node, char (*mods)[64], int mdepth, QCWrite *ws, int wn);
void qualify_colliding_consts(Compiler *c);
void qc_collect_class_writes(Compiler *c, int node, char (*path)[64], int depth, QCWrite **ws, int *n, int *cap);
void qualify_colliding_classes(Compiler *c);
void name_anon_block_kwrest(Compiler *c);
void rename_shadowing_block_params(Compiler *c);
void topup_forwarding_arity(Compiler *c);
void expand_struct_forwarding_super(Compiler *c);
void refuse_super_init_value(Compiler *c);
/* Defined in codegen.c; the analyzer uses it to specialize/type a
   `rescue <UserExc> => e` binding (#1415). */
int class_is_exc_subclass(Compiler *c, int ci);
int exc_subclass_defines(Compiler *c, const char *name);
/* Defined in codegen_fold.c; 1 if class `k` is `anc` or a descendant of it. */
int is_descendant(Compiler *c, int k, int anc);
/* Defined in codegen_fold.c; distinct implementations of `name` across cid's
   subtree. */
int dispatch_impl_count(Compiler *c, int cid, const char *name);
/* Defined in codegen_util.c; the proc-form clone of scope `s`, or -1. */
int scope_proc_form_of(Compiler *c, int s);
/* Defined in codegen_fold.c; the parameter a keyword hash binds as one more
   positional argument after `pos_argc` others, or -1. */
int kwh_arg_param(Compiler *c, Scope *m, int pos_argc);

/* --ext-entry designations (see codegen_internal.h / ext-design.md) */
extern const char *g_ext_entries;

/* the class every value of a boxed-value hash slot holds, or -1 (#4846) */
int hv_value_class(Compiler *c, int recv);
int comp_class_is_module(Compiler *c, ClassInfo *ci);
int is_builtin_reopen(const char *name);
char **dsend_candidates(Compiler *c, int *out_n);
int exc_reopen_definers(Compiler *c, const char *mname, int *out, int max);

#endif

